#ifndef CONFIGURATIONJEU_H_INCLUDED
#define CONFIGURATIONJEU_H_INCLUDED

#define TAILLE_INITIALE 20
#define PAS_DE_DEPLACEMENT 4
#define TAILLE_CELLULE 40
#define NOMBRE_CELLULE_LARGEUR 20
#define NOMBRE_CELLULE_HAUTEUR 20

#define STADE_LARGEUR TAILLE_CELLULE*NOMBRE_CELLULE_LARGEUR
#define STADE_HAUTEUR TAILLE_CELLULE*NOMBRE_CELLULE_HAUTEUR


#define FENETRE_LARGEUR TAILLE_CELLULE*NOMBRE_CELLULE_LARGEUR*1.2
#define FENETRE_HAUTEUR TAILLE_CELLULE*NOMBRE_CELLULE_HAUTEUR*1.2

// Pour la fenetre de saisie clavier

#define INPUT_MAX 100


#endif // CONFIGURATIONJEU_H_INCLUDED
